apiVersion: v1
kind: ConfigMap
metadata:
  name: cpu-pooler-configmap
data:
  cpu-pooler.yaml: |
    resourceBaseName: "nokia.k8s.io"
  poolconfig-controller.yaml: |
    pools: 
      cpupool1:
        cpus : "4,5"
        pooltype: "exclusive"
      cpupool2:
        cpus : "2,3"
        pooltype: "exclusive"
      sharedpool:
        cpus : "1"
        pooltype: "shared"
    nodeSelector:
      nodeType: controller
  poolconfig-dpdk.yaml: |
    pools: 
      cpupool1:
        cpus : "2,3,4,5,6,7"
        pooltype: "exclusive"
      sharedpool:
        cpus : "1"
        pooltype: "shared"
    nodeSelector:
      nodeType: dpdk
